---
- name: "udpate apt packages"
  become: yes
  apt:
    update_cache: yes
- name: "manual upgrade"
  become: yes
  shell:
    "dpkg --configure -a"
- name: "upgrade package"
  become: yes
  apt:
    upgrade: yes
- name: "install nodejs"
  become: yes
  apt:
    pkg:
      - nodejs
      - npm
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
- name: "Create web directory"
  become: yes
  file:
    path: ~/web
    state: directory
- name: "Copy file"
  copy:
    src: index.js
    dest: ~/web
- name: "Start web service"
  become: yes
  shell:
    "pm2 start ~/web/index.js -f"